[package]
authors = ["Pierre-Étienne Meunier <pe@pijul.org>"]
description = "A client and server SSH library."
documentation = "https://docs.rs/russh"
edition = "2018"
homepage = "https://pijul.org/russh"
include = [
  "Cargo.toml",
  "src/auth.rs",
  "src/compression.rs",
  "src/kex.rs",
  "src/key.rs",
  "src/lib.rs",
  "src/msg.rs",
  "src/negotiation.rs",
  "src/pty.rs",
  "src/session.rs",
  "src/sshbuffer.rs",
  "src/ssh_read.rs",
  "src/cipher/aes256gcm.rs",
  "src/cipher/chacha20poly1305.rs",
  "src/cipher/clear.rs",
  "src/cipher/mod.rs",
  "src/client/mod.rs",
  "src/client/session.rs",
  "src/client/encrypted.rs",
  "src/client/kex.rs",
  "src/client/proxy.rs",
  "src/server/mod.rs",
  "src/server/encrypted.rs",
  "src/server/kex.rs",
  "src/server/session.rs",
  "src/sodium.rs",
]
keywords = ["ssh"]
license = "Apache-2.0"
name = "russh"
readme = "../README.md"
repository = "https://nest.pijul.com/pijul/russh"
version = "0.34.0-beta.2"

[features]
default = ["flate2"]

[dependencies]
bitflags = "1.2"
byteorder = "1.3"
digest = "0.9"
flate2 = {version = "1.0", optional = true}
futures = "0.3"
generic-array = "0.14"
log = "0.4"
rust-crypto = "0.2.36"
hmac = "0.9.0"
openssl = {version = "0.10", optional = true}
rand = "0.8"
russh-cryptovec = {version = "0.7.0-beta.1", path = "../cryptovec"}
russh-keys = {version = "0.22.0-beta.1", path = "../russh-keys"}
russh-libsodium = {version = "0.3.0-beta.1", path = "../russh-libsodium"}
sha2 = "0.9"
thiserror = "1.0"
tokio = {version = "1.17.0", features = ["io-util", "rt-multi-thread", "time", "net", "sync", "macros", "process"]}

[dev-dependencies]
anyhow = "1.0"
env_logger = "0.7"
tokio = {version = "1.17.0", features = ["io-util", "rt-multi-thread", "time", "net", "sync", "macros"]}
